In [79]:
import json
from datetime import datetime
import numpy as np
import ezdxf
import pandas as pd
import os
from tqdm import tqdm

tqdm.pandas()

In [80]:
def obter_informacoes_arquivos(pasta):
    informacoes_arquivos = []

    for pasta_atual, sub_pastas, arquivos in tqdm(os.walk(pasta)):
        for arquivo in arquivos:
            caminho_completo = os.path.join(pasta_atual, arquivo)

            try:
                info = os.stat(caminho_completo)
            except (PermissionError, FileNotFoundError) as e:
                # Lidar com exceções (pular o arquivo e imprimir uma mensagem, se desejar)
                print(f"Erro ao obter informações de {caminho_completo}: {e}")
                continue

            # Extrair informações desejadas
            caminho_arquivo = caminho_completo
            arquivo, tipo_arquivo = os.path.splitext(arquivo)
            autor = info.st_uid
            data_criacao = datetime.fromtimestamp(info.st_ctime).strftime("%d/%m/%Y %H:%M")
            tempo_acesso = datetime.fromtimestamp(info.st_atime).strftime("%d/%m/%Y %H:%M")
            tempo_modificacao = datetime.fromtimestamp(info.st_mtime).strftime("%d/%m/%Y %H:%M")
            tempo_mudanca = datetime.fromtimestamp(info.st_ctime).strftime("%d/%m/%Y %H:%M")
            tamanho_arquivo = info.st_size

            # Criar um dicionário com as informações
            informacao_arquivo = {
                'caminho': caminho_arquivo,
                'arquivo': arquivo,
                'tipo_arquivo': tipo_arquivo,
                'data_criacao': data_criacao,
                'tempo_acesso': tempo_acesso,
                'tempo_modificacao': tempo_modificacao,
                'tempo_mudanca': tempo_mudanca,
                'tamanho': tamanho_arquivo
            }

            # Adicionar à lista de informações
            informacoes_arquivos.append(informacao_arquivo)
    print(informacoes_arquivos)
    return informacoes_arquivos

In [81]:
arquivos = obter_informacoes_arquivos('database\\projects\\CESAN 2025')

df = arquivos
df = pd.DataFrame(df)
#filtro = ~df['caminho'].str.contains('OLD|NOTAS|Notas|ANTIGO|RECEBIDOS', regex=True)
#df = df[filtro]
#filtro = df['caminho'].str.contains('CAD|REDE|MAP|PREF', regex=True)
#filtro = df['caminho'].str.contains('Furo', regex=True)
#df = df[filtro]
df = df.reset_index().drop(columns=['index'])
df

165it [00:00, 4404.35it/s]

[{'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\Cadastro_Drenagem_PMV_Av_Maruipe_Vitoria.dxf', 'arquivo': 'Cadastro_Drenagem_PMV_Av_Maruipe_Vitoria', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:01', 'tempo_acesso': '22/01/2025 21:55', 'tempo_modificacao': '22/01/2025 15:01', 'tempo_mudanca': '22/01/2025 15:01', 'tamanho': 11036794}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\Mapa de Vila Velha2 (2) - Copia.dxf', 'arquivo': 'Mapa de Vila Velha2 (2) - Copia', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 21:56', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 222585694}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\Planta Geral Municipio de Vila Velha.dxf', 'arquivo': 'Planta Geral Municipio de Vila Velha', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 21:59', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 10661714}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\Planta Geral Municipio de Vitória.dxf', 'arquivo': 'Planta Geral Municipio de Vitória', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:00', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 365453671}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\01. Vitória\\O-DVT_A.dxf', 'arquivo': 'O-DVT_A', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 14:59', 'tempo_acesso': '22/01/2025 22:13', 'tempo_modificacao': '22/01/2025 15:00', 'tempo_mudanca': '22/01/2025 14:59', 'tamanho': 425388002}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\01. Vitória\\O-DVT_E.dxf', 'arquivo': 'O-DVT_E', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:00', 'tempo_acesso': '22/01/2025 22:20', 'tempo_modificacao': '22/01/2025 15:00', 'tempo_mudanca': '22/01/2025 15:00', 'tamanho': 275725296}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\01. Vitória\\redes Vitória demanda Praia do Canto.dxf', 'arquivo': 'redes Vitória demanda Praia do Canto', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:00', 'tempo_acesso': '22/01/2025 22:25', 'tempo_modificacao': '22/01/2025 15:00', 'tempo_mudanca': '22/01/2025 15:00', 'tamanho': 28756758}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\01. Vitória\\Vitória Operacional_Água.dxf', 'arquivo': 'Vitória Operacional_Água', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:00', 'tempo_acesso': '22/01/2025 22:27', 'tempo_modificacao': '22/01/2025 15:01', 'tempo_mudanca': '22/01/2025 15:00', 'tamanho': 332310744}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\01. Vitória\\08. JOÃO DOS SANTOS FILHO\\JOÃO DOS SANTOS FILHO.dxf', 'arquivo': 'JOÃO DOS SANTOS FILHO', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 14:59', 'tempo_acesso': '22/01/2025 14:59', 'tempo_modificacao': '22/01/2025 14:59', 'tempo_mudanca': '22/01/2025 14:59', 'tamanho': 425416093}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\02. Guarapari\\Guarapari_Esgoto.dxf', 'arquivo': 'Guarapari_Esgoto', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:01', 'tempo_acesso': '22/01/2025 15:01', 'tempo_modificacao': '22/01/2025 15:01', 'tempo_mudanca': '22/01/2025 15:01', 'tamanho': 124128836}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\02. Guarapari\\O-DLT_A-_GUARAPARI[1].dxf', 'arquivo': 'O-DLT_A-_GUARAPARI[1]', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:01', 'tempo_acesso': '22/01/2025 15:01', 'tempo_modificacao': '22/01/2025 15:01', 'tempo_mudanca': '22/01/2025 15:01', 'tamanho': 219438691}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\03. Serra\\TRAVESSIA DN600 SERRA.dxf', 'arquivo': 'TRAVESSIA DN600 SERRA', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:01', 'tempo_acesso': '22/01/2025 15:01', 'tempo_modificacao': '22/01/2025 15:01', 'tempo_mudanca': '22/01/2025 15:01', 'tamanho': 101970374}, {'caminho': 'database\\projects\\CESAN 2025\\00. RECEBIDOS\\13. Aracruz\\DVT_A-ARACRUZ.dxf', 'arquivo': 'DVT_A-ARACRUZ', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:01', 'tempo_acesso': '22/01/2025 15:01', 'tempo_modificacao': '22/01/2025 15:01', 'tempo_mudanca': '22/01/2025 15:01', 'tamanho': 46833991}, {'caminho': 'database\\projects\\CESAN 2025\\01. CANTEIRO\\01. Serra - R. Florianópolis\\VIT-ARQ-CANTEIRO 01-R00.dxf', 'arquivo': 'VIT-ARQ-CANTEIRO 01-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 21:54', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 1280970}, {'caminho': 'database\\projects\\CESAN 2025\\01. CANTEIRO\\01. Serra - R. Florianópolis\\VIT-ARQ-CANTEIRO SERRA-R00.dxf', 'arquivo': 'VIT-ARQ-CANTEIRO SERRA-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 21:54', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 1516506}, {'caminho': 'database\\projects\\CESAN 2025\\01. CANTEIRO\\02. Serra - Av. Porto Dourado\\VIT-ARQ-CANTEIRO 02-R00.dxf', 'arquivo': 'VIT-ARQ-CANTEIRO 02-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 21:54', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 451175}, {'caminho': 'database\\projects\\CESAN 2025\\01. CANTEIRO\\03. Serra - Rua Braulina Baptista Lopes\\VIT-ARQ-CANTEIRO 03-R00.dxf', 'arquivo': 'VIT-ARQ-CANTEIRO 03-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 21:54', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 1625487}, {'caminho': 'database\\projects\\CESAN 2025\\01. CANTEIRO\\03. Serra - Rua Braulina Baptista Lopes\\VIT-ARQ-CANTEIRO 03-R01.dxf', 'arquivo': 'VIT-ARQ-CANTEIRO 03-R01', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 21:51', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 916217}, {'caminho': 'database\\projects\\CESAN 2025\\01. CANTEIRO\\ESCRITÓRIO - ENSEADA DO SUÁ\\LAYOUT.dxf', 'arquivo': 'LAYOUT', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 17:16', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 1540067}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\VIT-REDE-VITÓRIA-R00.dxf', 'arquivo': 'VIT-REDE-VITÓRIA-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:12', 'tempo_acesso': '22/01/2025 17:16', 'tempo_modificacao': '22/01/2025 15:12', 'tempo_mudanca': '22/01/2025 15:12', 'tamanho': 36020383}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 17:17', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 510732}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:32', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 314786}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:32', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 359462}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:32', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 3849120}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:32', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 371432}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:32', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 362104}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:32', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 1146619}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:32', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 364982}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\03. Cadastros Existentes\\VIT-CAD GERAL-AV. LEITÃO DA SILVA-R00.dxf', 'arquivo': 'VIT-CAD GERAL-AV. LEITÃO DA SILVA-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:32', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 28016058}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\VIT-REDE-AV. LEITÃO DA SILVA-R05.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R05', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:33', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 27798443}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\01. Estudo\\VIT-REDE-AV. LEITÃO DA SILVA-R00.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:33', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 2586902}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R00\\VIT-CIPP-AV. LEITÃO DA SILVA-R00.dxf', 'arquivo': 'VIT-CIPP-AV. LEITÃO DA SILVA-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:33', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 10660248}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R01\\VIT-REDE-AV. LEITÃO DA SILVA-R01.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R01', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:34', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 9480992}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R02\\VIT-REDE-AV. LEITÃO DA SILVA-R02.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R02', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:34', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 12626872}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R03\\VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO).dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO)', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:34', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 10665606}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R03\\VIT-REDE-AV. LEITÃO DA SILVA-R03.0.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R03.0', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:34', 'tempo_modificacao': '22/01/2025 15:02', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 10589535}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R03\\VIT-REDE-AV. LEITÃO DA SILVA-R04.1.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R04.1', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:02', 'tempo_acesso': '22/01/2025 22:35', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:02', 'tamanho': 10593138}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R04\\VIT-REDE-AV. LEITÃO DA SILVA-R04.0.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R04.0', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:35', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 27668875}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\07. Prefeitura\\VIT-PREF-AV. LEITÃO DA SILVA-R00.dxf', 'arquivo': 'VIT-PREF-AV. LEITÃO DA SILVA-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:35', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 2586902}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\07. Prefeitura\\FOTOS\\VIT-FOTOS-AV. LEITÃO DA SILVA-R00.dxf', 'arquivo': 'VIT-FOTOS-AV. LEITÃO DA SILVA-R00', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:35', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 2632379}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-04-22\\VIT-MAP-AV. LEITÃO DA SILVA-R01.dxf', 'arquivo': 'VIT-MAP-AV. LEITÃO DA SILVA-R01', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:35', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 1068466}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-05-17\\VIT-MAP-2024-05-17-AV. LEITÃO DA SILVA-R02.dxf', 'arquivo': 'VIT-MAP-2024-05-17-AV. LEITÃO DA SILVA-R02', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:36', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 27560481}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-05-17\\VIT-MAP-AV. LEITÃO DA SILVA-R02.dxf', 'arquivo': 'VIT-MAP-AV. LEITÃO DA SILVA-R02', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:36', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 27559383}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-06-15\\VIT-MAP-2024-06-15-AV. LEITÃO DA SILVA-R03.dxf', 'arquivo': 'VIT-MAP-2024-06-15-AV. LEITÃO DA SILVA-R03', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:37', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 27495650}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-07-29\\VIT-MAP-2024-07-29-AV. LEITÃO DA SILVA-R03.dxf', 'arquivo': 'VIT-MAP-2024-07-29-AV. LEITÃO DA SILVA-R03', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:37', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 27558045}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\11. Cadastro Final\\VIT-CAD-AV. LEITÃO DA SILVA-R01.dxf', 'arquivo': 'VIT-CAD-AV. LEITÃO DA SILVA-R01', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:38', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 64077432}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\CAIXAS CIRCULARES\\rev\\VIT-EST-VALA 1-ARMAÇÃO-R00-CIRCULAR.dxf', 'arquivo': 'VIT-EST-VALA 1-ARMAÇÃO-R00-CIRCULAR', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:40', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 2641617}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\CAIXAS CIRCULARES\\rev\\VIT-EST-VALA 1-FORMAS-R00-CIRCULAR.dxf', 'arquivo': 'VIT-EST-VALA 1-FORMAS-R00-CIRCULAR', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:40', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 1514688}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\CAIXAS CIRCULARES\\rev\\VIT-EST-VALA 2-ARMAÇÃO-R00-CIRCULAR.dxf', 'arquivo': 'VIT-EST-VALA 2-ARMAÇÃO-R00-CIRCULAR', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:40', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 2095971}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\CAIXAS CIRCULARES\\rev\\VIT-EST-VALA 2-FORMAS-R00-CIRCULAR.dxf', 'arquivo': 'VIT-EST-VALA 2-FORMAS-R00-CIRCULAR', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:40', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 1423061}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\CAIXAS CIRCULARES\\rev\\VIT-EST-VALA 3-ARMAÇÃO-R00-CIRCULAR.dxf', 'arquivo': 'VIT-EST-VALA 3-ARMAÇÃO-R00-CIRCULAR', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:40', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 2646223}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\CAIXAS CIRCULARES\\rev\\VIT-EST-VALA 3-FORMAS-R00-CIRCULAR.dxf', 'arquivo': 'VIT-EST-VALA 3-FORMAS-R00-CIRCULAR', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:40', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 1426933}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\CAIXAS CIRCULARES\\rev\\VIT-EST-VALA 4-ARMAÇÃO-R00-CIRCULAR.dxf', 'arquivo': 'VIT-EST-VALA 4-ARMAÇÃO-R00-CIRCULAR', 'tipo_arquivo': '.dxf', 'data_criacao': '22/01/2025 15:03', 'tempo_acesso': '22/01/2025 22:40', 'tempo_modificacao': '22/01/2025 15:03', 'tempo_mudanca': '22/01/2025 15:03', 'tamanho': 2644053}, {'caminho': 'database\\projects\\CESAN 2025\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. P

,caminho,arquivo,tipo_arquivo,data_criacao,tempo_acesso,tempo_modificacao,tempo_mudanca,tamanho
0,database\projects\CESAN 2025\00. RECEBIDOS\Cad...,Cadastro_Drenagem_PMV_Av_Maruipe_Vitoria,.dxf,22/01/2025 15:01,22/01/2025 21:55,22/01/2025 15:01,22/01/2025 15:01,11036794
1,database\projects\CESAN 2025\00. RECEBIDOS\Map...,Mapa de Vila Velha2 (2) - Copia,.dxf,22/01/2025 15:02,22/01/2025 21:56,22/01/2025 15:02,22/01/2025 15:02,222585694
2,database\projects\CESAN 2025\00. RECEBIDOS\Pla...,Planta Geral Municipio de Vila Velha,.dxf,22/01/2025 15:02,22/01/2025 21:59,22/01/2025 15:02,22/01/2025 15:02,10661714
3,database\projects\CESAN 2025\00. RECEBIDOS\Pla...,Planta Geral Municipio de Vitória,.dxf,22/01/2025 15:02,22/01/2025 22:00,22/01/2025 15:02,22/01/2025 15:02,365453671
4,database\projects\CESAN 2025\00. RECEBIDOS\01....,O-DVT_A,.dxf,22/01/2025 14:59,22/01/2025 22:13,22/01/2025 15:00,22/01/2025 14:59,425388002
...,...,...,...,...,...,...,...,...
379,database\projects\CESAN 2025\07. ARACRUZ\05. P...,ROD. ES 010,.dxf,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,51760565
380,database\projects\CESAN 2025\07. ARACRUZ\05. P...,RUA UBERLANDIA,.dxf,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,14026374
381,database\projects\CESAN 2025\RIKHELMY\VIT-ASF-...,VIT-ASF-BM02-LEITÃO DA SILVA-R03,.dxf,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,2807636
382,database\projects\CESAN 2025\RIKHELMY\VIT-ASF-...,VIT-ASF-BM03-LEITÃO DA SILVA-R03,.dxf,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,2804797
383,database\projects\CESAN 2025\RIKHELMY\VIT-ASF-...,VIT-ASF-BM05-LEITÃO DA SILVA-R03,.dxf,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,2804799

In [82]:
# Converter a coluna para datetime (caso necessário)
df['data_criacao'] = pd.to_datetime(df['tempo_modificacao'], format='%d/%m/%Y %H:%M')

# Definir a data de corte
data_corte = pd.to_datetime('03/01/2025 00:00', format='%d/%m/%Y %H:%M')

# Filtrar para datas maiores que o corte
df = df[df['data_criacao'] > data_corte]
df = df.reset_index()
df = df.drop(columns=['index'])
df

,caminho,arquivo,tipo_arquivo,data_criacao,tempo_acesso,tempo_modificacao,tempo_mudanca,tamanho
0,database\projects\CESAN 2025\00. RECEBIDOS\Cad...,Cadastro_Drenagem_PMV_Av_Maruipe_Vitoria,.dxf,2025-01-22 15:01:00,22/01/2025 21:55,22/01/2025 15:01,22/01/2025 15:01,11036794
1,database\projects\CESAN 2025\00. RECEBIDOS\Map...,Mapa de Vila Velha2 (2) - Copia,.dxf,2025-01-22 15:02:00,22/01/2025 21:56,22/01/2025 15:02,22/01/2025 15:02,222585694
2,database\projects\CESAN 2025\00. RECEBIDOS\Pla...,Planta Geral Municipio de Vila Velha,.dxf,2025-01-22 15:02:00,22/01/2025 21:59,22/01/2025 15:02,22/01/2025 15:02,10661714
3,database\projects\CESAN 2025\00. RECEBIDOS\Pla...,Planta Geral Municipio de Vitória,.dxf,2025-01-22 15:02:00,22/01/2025 22:00,22/01/2025 15:02,22/01/2025 15:02,365453671
4,database\projects\CESAN 2025\00. RECEBIDOS\01....,O-DVT_A,.dxf,2025-01-22 15:00:00,22/01/2025 22:13,22/01/2025 15:00,22/01/2025 14:59,425388002
...,...,...,...,...,...,...,...,...
379,database\projects\CESAN 2025\07. ARACRUZ\05. P...,ROD. ES 010,.dxf,2025-01-22 15:19:00,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,51760565
380,database\projects\CESAN 2025\07. ARACRUZ\05. P...,RUA UBERLANDIA,.dxf,2025-01-22 15:19:00,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,14026374
381,database\projects\CESAN 2025\RIKHELMY\VIT-ASF-...,VIT-ASF-BM02-LEITÃO DA SILVA-R03,.dxf,2025-01-22 15:19:00,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,2807636
382,database\projects\CESAN 2025\RIKHELMY\VIT-ASF-...,VIT-ASF-BM03-LEITÃO DA SILVA-R03,.dxf,2025-01-22 15:19:00,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,2804797
383,database\projects\CESAN 2025\RIKHELMY\VIT-ASF-...,VIT-ASF-BM05-LEITÃO DA SILVA-R03,.dxf,2025-01-22 15:19:00,22/01/2025 15:19,22/01/2025 15:19,22/01/2025 15:19,2804799

In [83]:
import numpy as np

def calcular_comprimento_vetorial(coordenadas):
    # Converte a lista de coordenadas em um array numpy
    coords = np.array(coordenadas)
    
    # Calcula as diferenças entre pontos consecutivos
    diffs = np.diff(coords, axis=0)
    
    # Calcula a norma (distância euclidiana) de cada diferença e soma para obter o comprimento
    comprimento = np.sum(np.linalg.norm(diffs, axis=1))
    
    return comprimento

In [84]:
# Função para converter atributos para um formato serializável
def convert_to_serializable(value):
    if isinstance(value, (list, tuple)):
        return [convert_to_serializable(v) for v in value]
    elif isinstance(value, dict):
        return {k: convert_to_serializable(v) for k, v in value.items()}
    elif isinstance(value, (int, float, str, bool, type(None))):
        return value
    elif callable(value):
        return str(value)  # Converte funções e métodos para strings
    elif hasattr(value, '__dict__'):
        return convert_to_serializable(value.__dict__)
    else:
        return str(value)

In [85]:
# Função para extrair dados genéricos de qualquer entidade DXF
def extract_entity_data(entity):
    data = {'type': entity.dxftype()}
    for attr in dir(entity.dxf):
        if not attr.startswith('_'):
            try:
                data[attr] = getattr(entity.dxf, attr)
            except AttributeError:
                data[attr] = None
    return data

In [86]:
# Função para extrair dados genéricos de qualquer entidade DXF
def extract_entity_data(entity, space):
    data = {'type': entity.dxftype()}
    
    # Adiciona informações sobre o espaço (Model ou Layout)
    data['space'] = space

    # Adiciona verificação para salvar dados de blocos (INSERT)
    if entity.dxftype() == 'INSERT':
        data['block_name'] = entity.dxf.name  # Nome do bloco
        data['handle'] = entity.dxf.handle    # Handle do bloco
        data['insertion_point'] = (entity.dxf.insert.x, entity.dxf.insert.y, entity.dxf.insert.z)  # Ponto de inserção
        data['rotation'] = entity.dxf.rotation  # Rotação
        data['xscale'] = entity.dxf.xscale  # Escala em X
        data['yscale'] = entity.dxf.yscale  # Escala em Y
        data['zscale'] = entity.dxf.zscale  # Escala em Z

        # Extrair atributos de blocos, se houver
        if hasattr(entity, 'attribs') and entity.attribs:
            data['attributes'] = {att.dxf.tag: att.dxf.text for att in entity.attribs}
    
    # Adiciona verificação para salvar coordenadas de polilinhas
    elif entity.dxftype() == 'LWPOLYLINE':
        data['coordinates'] = [(float(point[0]), float(point[1]), float(point[2])) for point in entity]
        data['is_closed'] = entity.closed  # Verifica se a polilinha é fechada
        data['length'] = calcular_comprimento_vetorial(data['coordinates'])
  
    elif entity.dxftype() == 'POLYLINE':
        data['coordinates'] = [(vertex.dxf.location.x, vertex.dxf.location.y,  vertex.dxf.location.z) for vertex in entity.vertices]
        data['is_closed'] = entity.is_closed  # Verifica se a polilinha é fechada
        data['length'] = calcular_comprimento_vetorial(data['coordinates']) # Comprimento da polilinha

    elif entity.dxftype() == 'LINE':
        start = entity.dxf.start
        end = entity.dxf.end
        data['coordinates'] = [(start.x, start.y, start.z), (end.x, end.y, end.z)]
        data['length'] = entity.dxf.start.distance(end)  # Comprimento da linha   
         
    # Arcos e Círculos
    elif entity.dxftype() in ['CIRCLE', 'ARC']:
        data['center'] = (entity.dxf.center.x, entity.dxf.center.y, entity.dxf.center.z)
        data['radius'] = entity.dxf.radius
        if entity.dxftype() == 'ARC':
            data['start_angle'] = entity.dxf.start_angle
            data['end_angle'] = entity.dxf.end_angle
            
    # Extrai outros atributos
    for attr in dir(entity.dxf):
        if not attr.startswith('_'):
            try:
                value = getattr(entity.dxf, attr)
                data[attr] = convert_to_serializable(value)
            except AttributeError:
                data[attr] = None
    
    return data

In [87]:
# Função para salvar os dados em um DataFrame
def save_to_dataframe(dxf_file):
    doc = ezdxf.readfile(dxf_file)
    
    entities_data = []
    
    # Coletar dados de todas as entidades no Model Space
    for entity in doc.modelspace():
        entity_data = extract_entity_data(entity, 'Model Space')
        entities_data.append(entity_data)
    
    # Coletar dados de todas as entidades em cada Layout
    for layout in doc.layouts:
        for entity in layout:
            entity_data = extract_entity_data(entity, layout.name)  # Nome do Layout
            entities_data.append(entity_data)
    
    # Criar o DataFrame com os dados das entidades
    df = pd.DataFrame(entities_data)
    return df

In [88]:
import os
import pandas as pd
from tqdm import tqdm  # Importando corretamente

# Configurações de pastas
folder_origin = 'database\\projects'
folder_output = 'database\\projects data'

# Listas para metadados
data = {
    'arquivo': [],
    'categoria': [],
    'Lin': [],
    'Col': []
}

# Função para salvar metadados
def salvar_metadados(arquivo, categoria, df):
    data['arquivo'].append(arquivo)
    data['categoria'].append(categoria)
    data['Lin'].append(df.shape[0])
    data['Col'].append(df.shape[1])

# Função principal de processamento
def processar_arquivo(caminho):
    df = save_to_dataframe(caminho)
    caminho_relativo = os.path.relpath(caminho, folder_origin)
    caminho_destino = os.path.join(folder_output, caminho_relativo).replace('.dxf', '')

    # Cria as subpastas necessárias (apenas uma vez por arquivo)
    os.makedirs(os.path.dirname(caminho_destino), exist_ok=True)

    # Extrai o nome do arquivo
    arquivo = os.path.basename(caminho_destino)
    # Identificar colunas que contêm qualquer valor começando com "<" em todo o DataFrame
    cols_to_drop = df.columns[(df.astype(str).apply(lambda x: x.str.startswith('<'))).any()]
    # Remover as colunas identificadas
    df = df.drop(columns=cols_to_drop)
    caminho_destino = f'\\\\?\\{os.path.abspath(caminho_destino)}'


    #print(caminho_destino)
    #print(arquivo)

    # Cria o ExcelWriter e salva cada categoria em uma aba
    with pd.ExcelWriter(f'{caminho_destino}.xlsx', engine='xlsxwriter') as writer:
        salvar_metadados(arquivo, 'Original', df)  # Metadados do arquivo completo

        # Itera pelas categorias e salva em abas separadas
        for categoria in df['type'].unique():
            df_categoria = df[df['type'] == categoria].dropna(axis=1, how='all')
            salvar_metadados(arquivo, categoria, df_categoria)
            df_categoria.to_excel(writer, sheet_name=categoria, index=False)



    #print(f'Dados Extraídos de: {arquivo}')

df = df[139:]

# Inicializa o tqdm
with tqdm(total=len(df), desc='Processando arquivos', unit='arquivo') as pbar:
    for _, linha in df.iterrows():
        # Atualiza o tqdm com o nome do arquivo atual e tamanho
        pbar.set_postfix({
            "Arquivo Atual": os.path.basename(linha['caminho']),
            "Tamanho": linha['tamanho']
        })

        # Simula o processamento de cada arquivo
        processar_arquivo(linha['caminho'])
        # Aqui você incluiria a lógica de cópia ou outras ações
        pbar.update(1)  # Incrementa o progresso

# Criando DataFrame final com metadados
df_metadados = pd.DataFrame(data)
display(df_metadados)

df_metadados.to_excel('database\\projects data\\CESAN 2025\\CESAN 2025.xlsx')

Processando arquivos: 100%|██████████| 245/245 [1:09:43<00:00, 17.08s/arquivo, Arquivo Atual=VIT-ASF-BM05-LEITÃO DA SILVA-R03.dxf, Tamanho=2.8e+6]

                               arquivo   categoria   Lin  Col
0       VIT-RAMAL-07-RB-Y20L437661-R02    Original  9635  115
1       VIT-RAMAL-07-RB-Y20L437661-R02        TEXT   392   30
2       VIT-RAMAL-07-RB-Y20L437661-R02      INSERT  3614   33
3       VIT-RAMAL-07-RB-Y20L437661-R02   DIMENSION   840   36
4       VIT-RAMAL-07-RB-Y20L437661-R02  LWPOLYLINE  3106   30
...                                ...         ...   ...  ...
2586  VIT-ASF-BM05-LEITÃO DA SILVA-R03       POINT    54   22
2587  VIT-ASF-BM05-LEITÃO DA SILVA-R03        LINE     6   27
2588  VIT-ASF-BM05-LEITÃO DA SILVA-R03    VIEWPORT     2   59
2589  VIT-ASF-BM05-LEITÃO DA SILVA-R03     WIPEOUT     2   39
2590  VIT-ASF-BM05-LEITÃO DA SILVA-R03       HATCH     4   33

[2591 rows x 4 columns]

In [89]:
print(pd.io.excel._base.ExcelWriter.__doc__)

Class for writing DataFrame objects into excel sheets.

Default is to use:

* `xlsxwriter <https://pypi.org/project/XlsxWriter/>`__ for xlsx files if xlsxwriter
  is installed otherwise `openpyxl <https://pypi.org/project/openpyxl/>`__
* `odswriter <https://pypi.org/project/odswriter/>`__ for ods files

See ``DataFrame.to_excel`` for typical usage.

The writer should be used as a context manager. Otherwise, call `close()` to save
and close any opened file handles.

Parameters
----------
path : str or typing.BinaryIO
    Path to xls or xlsx or ods file.
engine : str (optional)
    Engine to use for writing. If None, defaults to
    ``io.excel.<extension>.writer``.  NOTE: can only be passed as a keyword
    argument.
date_format : str, default None
    Format string for dates written into Excel files (e.g. 'YYYY-MM-DD').
datetime_format : str, default None
    Format string for datetime objects written into Excel files.
    (e.g. 'YYYY-MM-DD HH:MM:SS').
mode : {'w', 'a'}, default 'w'
    File mode to use (write or append). Append does not work with fsspec URLs.
storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

if_sheet_exists : {'error', 'new', 'replace', 'overlay'}, default 'error'
    How to behave when trying to write to a sheet that already
    exists (append mode only).

    * error: raise a ValueError.
    * new: Create a new sheet, with a name determined by the engine.
    * replace: Delete the contents of the sheet before writing to it.
    * overlay: Write contents to the existing sheet without first removing,
      but possibly over top of, the existing contents.

    .. versionadded:: 1.3.0

    .. versionchanged:: 1.4.0

       Added ``overlay`` option

engine_kwargs : dict, optional
    Keyword arguments to be passed into the engine. These will be passed to
    the following functions of the respective engines:

    * xlsxwriter: ``xlsxwriter.Workbook(file, **engine_kwargs)``
    * openpyxl (write mode): ``openpyxl.Workbook(**engine_kwargs)``
    * openpyxl (append mode): ``openpyxl.load_workbook(file, **engine_kwargs)``
    * odswriter: ``odf.opendocument.OpenDocumentSpreadsheet(**engine_kwargs)``

    .. versionadded:: 1.3.0

Notes
-----
For compatibility with CSV writers, ExcelWriter serializes lists
and dicts to strings before writing.

Examples
--------
Default usage:

>>> df = pd.DataFrame([["ABC", "XYZ"]], columns=["Foo", "Bar"])  # doctest: +SKIP
>>> with pd.ExcelWriter("path_to_file.xlsx") as writer:
...     df.to_excel(writer)  # doctest: +SKIP

To write to separate sheets in a single file:

>>> df1 = pd.DataFrame([["AAA", "BBB"]], columns=["Spam", "Egg"])  # doctest: +SKIP
>>> df2 = pd.DataFrame([["ABC", "XYZ"]], columns=["Foo", "Bar"])  # doctest: +SKIP
>>> with pd.ExcelWriter("path_to_file.xlsx") as writer:
...     df1.to_excel(writer, sheet_name="Sheet1")  # doctest: +SKIP
...     df2.to_excel(writer, sheet_name="Sheet2")  # doctest: +SKIP

You can set the date format or datetime format:

>>> from datetime import date, datetime  # doctest: +SKIP
>>> df = pd.DataFrame(
...     [
...         [date(2014, 1, 31), date(1999, 9, 24)],
...         [datetime(1998, 5, 26, 23, 33, 4), datetime(2014, 2, 28, 13, 5, 13)],
...     ],
...     index=["Date", "Datetime"],
...     columns=["X", "Y"],
... )  # doctest: +SKIP
>>> with pd.ExcelWriter(
...     "path_to_file.xlsx",
...     date_format="YYYY-MM-DD",
...     datetime_format="YYYY-MM-DD HH:MM:SS"
... ) as writer:
...     df.to_excel(writer)  # doctest: +SKIP

You can also append to an existing Excel file:

>>> with pd.ExcelWriter("path_to_file.xlsx", mode="a", engine="openpyxl") as writer:
...     df.to_excel(writer, sheet_name="Sheet3")  # doctest: +SKIP

Here, the `if_sheet_exists` parameter can be set to replace a sheet if it
already exists:

>>> with ExcelWriter(
...     "path_to_file.xlsx",
...     mode="a",
...     engine="openpyxl",
...     if_sheet_exists="replace",
... ) as writer:
...     df.to_excel(writer, sheet_name="Sheet1")  # doctest: +SKIP

You can also write multiple DataFrames to a single sheet. Note that the
``if_sheet_exists`` parameter needs to be set to ``overlay``:

>>> with ExcelWriter("path_to_file.xlsx",
...     mode="a",
...     engine="openpyxl",
...     if_sheet_exists="overlay",
... ) as writer:
...     df1.to_excel(writer, sheet_name="Sheet1")
...     df2.to_excel(writer, sheet_name="Sheet1", startcol=3)  # doctest: +SKIP

You can store Excel file in RAM:

>>> import io
>>> df = pd.DataFrame([["ABC", "XYZ"]], columns=["Foo", "Bar"])
>>> buffer = io.BytesIO()
>>> with pd.ExcelWriter(buffer) as writer:
...     df.to_excel(writer)

You can pack Excel file into zip archive:

>>> import zipfile  # doctest: +SKIP
>>> df = pd.DataFrame([["ABC", "XYZ"]], columns=["Foo", "Bar"])  # doctest: +SKIP
>>> with zipfile.ZipFile("path_to_file.zip", "w") as zf:
...     with zf.open("filename.xlsx", "w") as buffer:
...         with pd.ExcelWriter(buffer) as writer:
...             df.to_excel(writer)  # doctest: +SKIP

You can specify additional arguments to the underlying engine:

>>> with pd.ExcelWriter(
...     "path_to_file.xlsx",
...     engine="xlsxwriter",
...     engine_kwargs={"options": {"nan_inf_to_errors": True}}
... ) as writer:
...     df.to_excel(writer)  # doctest: +SKIP

In append mode, ``engine_kwargs`` are passed through to
openpyxl's ``load_workbook``:

>>> with pd.ExcelWriter(
...     "path_to_file.xlsx",
...     engine="openpyxl",
...     mode="a",
...     engine_kwargs={"keep_vba": True}
... ) as writer:
...     df.to_excel(writer, sheet_name="Sheet2")  # doctest: +SKIP

In [90]:
def deletar_pastas_vazias(diretorio_raiz):
    # Percorre a estrutura de diretórios de baixo para cima (bottom-up)
    for root, dirs, files in os.walk(diretorio_raiz, topdown=False):
        for dir_name in dirs:
            caminho_completo = os.path.join(root, dir_name)

            # Tenta remover a pasta, se estiver vazia
            try:
                os.rmdir(caminho_completo)
                print(f"Pasta vazia deletada: {caminho_completo}")
            except OSError as e:
                # Se não puder deletar, provavelmente não está vazia
                #print(f"Erro ao deletar {caminho_completo}: {e}")
                e

# Exemplo de uso
diretorio = r"C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects data"  # Substituir pelo caminho desejado
deletar_pastas_vazias(diretorio)